
export const FETCH_ALL_HISTORY_REQUESTED = 'FETCH_ALL_HISTORY_REQUESTED';
export const FETCH_ALL_HISTORY_SUCCESS = 'FETCH_ALL_HISTORY_SUCCESS';
export const FETCH_ALL_HISTORY_FAILURE = 'FETCH_ALL_HISTORY_FAILURE';
