export const FETCH_ALL_LAUNCHES_REQUESTED = 'FETCH_ALL_LAUNCHES_REQUESTED';
export const FETCH_ALL_LAUNCHES_SUCCESS = 'FETCH_ALL_LAUNCHES_SUCCESS';
export const FETCH_ALL_LAUNCHES_FAILURE = 'FETCH_ALL_LAUNCHES_FAILURE';

export const FETCH_DETAILS_REQUESTED = 'FETCH_DETAILS_REQUESTED';
export const FETCH_DETAILS_SUCCESS = 'FETCH_DETAILS_SUCCESS';
export const FETCH_DETAILS_FAILURE = 'FETCH_DETAILS_FAILURE';
